#!/bin/bash

PKG_HOME=$(hab pkg path bbh/nginx)

directory ()
{
  if [ -e ${1} ]; then
    rm -rfv ${1}
  fi
  mkdir -p ${1}
}

directory {{pkg.svc_var_path}}/www
cp -rv ${PKG_HOME}/www/* {{pkg.svc_var_path}}/www/
chmod 755 {{pkg.svc_var_path}}/www
chmod 755 {{pkg.svc_var_path}}

exec ${PKG_HOME}/sbin/nginx 2>&1
