#!/bin/bash

PKG_HOME=$(hab pkg path bbh/php5)

symlink ()
{
  if [ -e ${2} ]; then
    rm -rfv ${2}
  fi
  ln -sv ${1} ${2}
}

directory ()
{
  if [ ! -d ${1} ]; then
    mkdir -p ${1}
  fi
}

directory {{pkg.svc_path}}/var/run
directory {{pkg.svc_path}}/var/log
chown -R hab:hab {{pkg.svc_path}}/var/log
symlink {{pkg.svc_path}}/var/log {{pkg.svc_path}}/log

exec ${PKG_HOME}/sbin/php-fpm -F 2>&1
